title: "MASK INTELLIGENCE"
email: maskintelligence@gmail.com
description: >-
  Mask Intelligence is your dedicated partner for digital transformation.
  We specialize in translating business vision into powerful, custom-built
  online realitiesâ€”from professional websites and e-commerce stores to
  complex web applications and analytics dashboards.

  We believe every business has unique potential waiting to be unlocked.
  Our mission is to remove the barriers of digital complexity.

url: "https://maskintelligence.github.io"
baseurl: ""

twitter_username: MASKINTELL
github_username: maskintelligence-gif

minimal_mistakes_skin: default
search: true

markdown: kramdown
theme: minimal-mistakes-jekyll

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

timezone: Africa/Kampala

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "TEAM MASK"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "We are amazed if our articles help you."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mask-intelligence.web.app"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MASKINTELL"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maskintelligence-gif"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MASKINTELL"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maskintelligence-gif"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
